const animations = {
  outRight: "animate__animated animate__bounceOutRight",
  outDown: "animate__animated animate__bounceOutDown",
  inDown: "animate__animated animate__bounceInDown",
  bounceIn: "animate__animated animate__bounceIn",
  inLeft: "animate__animated animate__bounceInLeft",
  inUp: "animate__animated animate__bounceInUp",
  flipIn: "animate__animated animate__zoomIn",
  pulse: "animate__animated animate__pulse",
  fadeInDown: "animate__animated animate__fadeInDown",
  fadeOut: "animate__animated animate__fadeOut",
  fadeOutRight: "animate__animated animate__fadeOutRight",
  fadeOutDown: "animate__animated animate__fadeOutDown",
  rotateIn: "animate__animated animate__rotateIn",
  fadeIn: "animate__animated animate__fadeIn",
  attention: "animate__animated animate__rubberBand",
  shake: "animate__animated animate__shakeX",
  hinge: "animate__animated animate__hinge",
  delay1: "animate__delay-1s",
  delay2: "animate__delay-2s",
  delay3: "animate__delay-3s",
  delay4: "animate__delay-4s",
  delay5: "animate__delay-5s",
};

export default animations ;
